import Head from "next/head";
import { useState } from "react";
import { Container, Grid } from "@mantine/core";
import type { Comment, Reply } from "@/types/commentType";
import { ImageWithComments } from "@/components/ImageWithComments/ImageWithComments";
import { CommentList } from "@/components/CommentList/CommentList";

export default function Home() {
  const [comments, setComments] = useState<Comment[]>([]);

  const handleAddComment = (comment: Comment) => {
    setComments((prev) => [...prev, comment]);
  };

  const handleAddReply = (commentId: string, reply: Reply) => {
    setComments((prev) =>
      prev.map((c) =>
        c.id === commentId ? { ...c, replies: [...c.replies, reply] } : c
      )
    );
  };

  return (
    <>
      <Head>
        <title>Comment Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Container my="md">
          <Grid>
            <ImageWithComments
              onAddComment={handleAddComment}
              comments={comments}
            />
            <CommentList comments={comments} onAddReply={handleAddReply} />
          </Grid>
        </Container>
      </div>
    </>
  );
}
